---
version: '3.3'

services:
  proxy:
    build:
      context: ../
      dockerfile: build/package/docker/Dockerfile
    networks:
      default:
        aliases: [squid.proxy]
    volumes:
      - "../certs:/etc/squid/ssl_cert"

  client:
    build:
      context: ../
      dockerfile: build/package/docker/Dockerfile.client
    environment:
      http_proxy: http://squid.proxy:8888
      https_proxy: http://squid.proxy:8888
    depends_on:
      - proxy
    networks:
      default:
        aliases: [my.client]
    volumes:
      - "../certs:/usr/local/share/ca-certificates"

networks:
  default:
